# This is an Example
# smeltable-items:
# COBBLESTONE: STONE
# Left is the item to smelt
# Right is the item to give when smelted
# Please consider giving a star, it will help a lot ♥️! ^^
# Github : https://github.com/XPaladiumyX/CustomCommandsPlugin
# Discord Community : https://discord.gg/pTErYjTh5h


# The main plugin prefix.
Prefix: "§dSky X §9Network §bCOMMANDS §8●⏺&7"
# REFER TO https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html FOR MATERIAL LIST
smeltable-items:
  IRON_ORE: IRON_INGOT
  GOLD_ORE: GOLD_INGOT
  SAND: GLASS
# Possible placeholders :
# - %input%
# - %output%
messages:
  smelt-success: "§aYou have melted §f%input% §aand obtained §f%output%."
  smelt-fail: "§cThis item cannot be melted."
