name: CustomCommandsPlugin
version: '1.2-FINAL'
main: skyxnetwork.customCommandsPlugin.CustomCommandsPlugin
api-version: '1.20'
description: Plugin adding /craft, /ec, /enderchest, and /smelt commands.
commands:
  craft:
    description: Opens a virtual crafting table.
    usage: /craft
  ec:
    description: Open your EnderChest.
    usage: /ec
  enderchest:
    description: Open your EnderChest.
    usage: /enderchest
  smelt:
    description: Melts the item in your hand.
    usage: /smelt
  customcommandsplugin:
    description: Commands to reload the CustomCommandsPlugin plugin.
    usage: /customcommandsplugin reload
permissions:
  skyxnetwork.customcommandsplugin.*:
    description: Permission to bypass all commands.
    default: false
  skyxnetwork.customcommandsplugin.reload:
    description: Permission to reload the plugin.
    default: false
  skyxnetwork.customcommandsplugin.craft:
    description: Permission to run the /craft command.
    default: false
  skyxnetwork.customcommandsplugin.enderchest:
    description: Permission to execute /enderchest and /ec commands.
    default: false
  skyxnetwork.customcommandsplugin.smelt:
    description: Permission to execute the /smelt command.
    default: false
# Plugin settings
Prefix: "§dSky X §9Network §bCOMMANDS §8●⏺§7"