name: CustomCommandsPlugin
version: '1.2-FINAL'
main: skyxnetwork.customCommandsPlugin.CustomCommandsPlugin
api-version: '1.20'
description: Plugin adding /craft, /ec, /enderchest, and /smelt commands.
commands:
  craft:
    description: Opens a virtual crafting table.
    usage: /craft
  ec:
    description: Open your EnderChest.
    usage: /ec
  enderchest:
    description: Open your EnderChest.
    usage: /enderchest
  smelt:
    description: Melts the item in your hand.
    usage: /smelt
  customcommandsplugin:
    description: Commands to reload the CustomCommandsPlugin plugin.
    usage: /customcommandsplugin reload
permissions:
  skyxnetwork.customcommandsplugin.*:
    description: Permission pour bypass toutes les commandes.
    default: op
  skyxnetwork.customcommandsplugin.reload:
    description: Permission pour recharger le plugin.
    default: op
  skyxnetwork.customcommandsplugin.craft:
    description: Permission pour exécuter la commande /craft.
    default: true
  skyxnetwork.customcommandsplugin.enderchest:
    description: Permission pour exécuter les commandes /enderchest et /ec.
    default: true
  skyxnetwork.customcommandsplugin.smelt:
    description: Permission pour exécuter la commande /smelt.
    default: true